name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  GO_VERSION: "1.25.1"

jobs:
  build:
    name: Build - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          # Linux AMD64
          - os: linux
            arch: amd64
            runner: ubuntu-latest
            artifact_name: survey-system-linux-amd64

          # Linux ARM64
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            artifact_name: survey-system-linux-arm64

          # macOS AMD64 (Intel)
          - os: darwin
            arch: amd64
            runner: macos-13
            artifact_name: survey-system-darwin-amd64

          # macOS ARM64 (Apple Silicon)
          - os: darwin
            arch: arm64
            runner: macos-latest
            artifact_name: survey-system-darwin-arm64

          # Windows AMD64
          - os: windows
            arch: amd64
            runner: windows-latest
            artifact_name: survey-system-windows-amd64.exe

          # Windows ARM64
          - os: windows
            arch: arm64
            runner: windows-latest
            artifact_name: survey-system-windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p dist
          go build -ldflags="-s -w" -o dist/${{ matrix.artifact_name }} ./cmd/server
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
          retention-days: 30
