name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GO_VERSION: "1.25.1"

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          mkdir -p dist

          # Linux AMD64
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-linux-amd64 ./cmd/server

          # Linux ARM64
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-linux-arm64 ./cmd/server

          # macOS AMD64
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-darwin-amd64 ./cmd/server

          # macOS ARM64
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-darwin-arm64 ./cmd/server

          # Windows AMD64
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-windows-amd64.exe ./cmd/server

          # Windows ARM64
          GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/survey-system-windows-arm64.exe ./cmd/server

      - name: Create archives
        run: |
          cd dist
          tar -czf survey-system-linux-amd64.tar.gz survey-system-linux-amd64
          tar -czf survey-system-linux-arm64.tar.gz survey-system-linux-arm64
          tar -czf survey-system-darwin-amd64.tar.gz survey-system-darwin-amd64
          tar -czf survey-system-darwin-arm64.tar.gz survey-system-darwin-arm64
          zip survey-system-windows-amd64.zip survey-system-windows-amd64.exe
          zip survey-system-windows-arm64.zip survey-system-windows-arm64.exe
          sha256sum *.tar.gz *.zip > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
